export const surpriseMePrompts = [
    'A serene mountain landscape at sunset',
    'A futuristic cityscape with flying cars',
    'A magical underwater kingdom with vibrant coral reefs',
    'A mystical forest with glowing mushrooms',
    'An ancient castle perched on a cliff',
    'A bustling market in a vibrant foreign city',
    'A tranquil beach with palm trees and crystal-clear water',
    'A cozy cabin in the snowy woods',
    'A steampunk-inspired city with towering mechanical structures',
    'A whimsical garden filled with oversized flowers and plants',
    'A dramatic stormy sky with lightning bolts',
    'A group of majestic wild horses running through an open field',
    'An otherworldly alien landscape with strange rock formations',
    'A retro-inspired cityscape with neon signs and vintage cars',
    'A fantastical floating island with waterfalls cascading into the void',
    'A dense and mysterious fog covering a haunted forest',
    'A serene zen garden with raked sand and bonsai trees',
    'A magical library with towering shelves and floating books',
    'A picturesque vineyard with rows of grapevines and a charming farmhouse',
    'A futuristic space station orbiting a distant planet',
    'A surreal dreamlike scene with floating islands in the sky',
    'A tranquil lake surrounded by colorful autumn trees',
    'A whimsical village inhabited by friendly creatures and talking animals',
    'A grand and ornate cathedral with stained glass windows',
    'A sprawling fantasy kingdom with castles and rolling hills',
    'A futuristic cyberpunk city with skyscrapers and glowing neon lights',
    'A serene moonlit night over a calm lake',
    'A lush and vibrant rainforest teeming with exotic wildlife',
    'A serene Japanese garden with a traditional wooden bridge',
    'A hidden cave filled with glowing crystals and gemstones',
    'A vast and desolate desert with towering sand dunes',
    'A surreal underwater scene with floating jellyfish and colorful coral',
    'A peaceful countryside with fields of blooming flowers',
    'A futuristic transportation hub with high-speed trains and futuristic vehicles',
    'A picturesque coastal village with colorful fishing boats',
    'A whimsical carousel in a fairytale-like amusement park',
    'A mysterious ancient ruins hidden deep in the jungle',
    'A dramatic sunset over a rugged mountain range',
    'A peaceful farm with grazing animals and a red barn',
    'A vibrant and bustling street market with vendors and shoppers',
    'A futuristic laboratory with advanced technology and scientific equipment',
    'A charming European village with cobblestone streets and quaint houses',
    'A dramatic seascape with crashing waves and rocky cliffs',
    'A mystical floating city above the clouds',
    'A tranquil meditation retreat with peaceful gardens and water features',
    'A post-apocalyptic wasteland with remnants of a decaying civilization',
    'A lush vineyard with rows of grapevines and a wine cellar',
    'A magical winter wonderland with snow-covered trees and a cozy cottage',
    'A futuristic stadium filled with cheering fans and advanced holographic displays',
    'A breathtaking view of Earth from space with swirling clouds and city lights',
];